-- V1 初期スキーマ（Phase 1〜3 の実装済み分）
--
-- 対象Phase: Phase 1（players / player_settings / tower_clear_records / characters）
--            Phase 2（users / refresh_tokens / email_verification_tokens / equipment /
--                     character_equip_slots / inventory_items / battle_logs /
--                     shop_daily_states / shop_daily_slots）
--            Phase 3（party_members / learned_skills / active_skill_slots）
-- 変更概要: Alembic の既存5リビジョンを畳んだ初期スキーマ（java_migration.md §5）。
--
-- 定義の正は docs/tech/basic/tech_db.md と tech_db/ 配下。定義書に無いテーブル・列は作らない（§7）。
-- 未実装テーブル（prestige_bonuses / facilities / boss_rush_states / boss_rush_milestones）と
-- 未実装列（characters.rarity / tower_clear_records.highest_floor_at）は含めない。
--
-- 既定値はアプリ側（Entity フィールドの初期値）で付与するため DEFAULT 句を置かない（§4-2）。
-- 外部キーの参照動作は指定しない（DBMS 既定の NO ACTION。§5）。
-- 一意制約名は uq_<テーブル名>_<列>_<列>（§2）。主キー・外部キーの制約名は DBMS 既定に委ねる。

-- ---------------------------------------------------------------------------
-- 認証・アカウント（tech_db/auth.md）
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id             varchar(50)  NOT NULL,
    email          varchar(255),
    password_hash  varchar(255),
    google_id      varchar(255),
    display_name   varchar(100) NOT NULL,
    is_guest       boolean      NOT NULL,
    email_verified boolean      NOT NULL,
    created_at     timestamptz  NOT NULL,
    last_login_at  timestamptz  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_google_id UNIQUE (google_id)
);

CREATE TABLE refresh_tokens (
    id         integer      GENERATED BY DEFAULT AS IDENTITY,
    user_id    varchar(50)  NOT NULL REFERENCES users (id),
    token_hash varchar(255) NOT NULL,
    expires_at timestamptz  NOT NULL,
    revoked    boolean      NOT NULL,
    created_at timestamptz  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE TABLE email_verification_tokens (
    id         integer      GENERATED BY DEFAULT AS IDENTITY,
    user_id    varchar(50)  NOT NULL REFERENCES users (id),
    token_hash varchar(255) NOT NULL,
    purpose    varchar(20)  NOT NULL,
    expires_at timestamptz  NOT NULL,
    used       boolean      NOT NULL,
    created_at timestamptz  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_email_verification_tokens_token_hash UNIQUE (token_hash)
);

-- ---------------------------------------------------------------------------
-- プレイヤー・キャラクター（tech_db/player.md）
-- ---------------------------------------------------------------------------

CREATE TABLE players (
    id               varchar(36)      NOT NULL,
    user_id          varchar(50)      REFERENCES users (id),
    gold             bigint           NOT NULL,
    current_tower_id varchar(50),
    current_floor    integer,
    target_floor     integer,
    tower_mode       varchar(20)      NOT NULL,
    hp_threshold     double precision NOT NULL,
    current_enemy_id varchar(50),
    current_enemy_hp integer,
    run_gold         bigint           NOT NULL,
    highest_floor    integer          NOT NULL,
    last_tick_at     timestamptz      NOT NULL,
    created_at       timestamptz      NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_players_user_id UNIQUE (user_id)
);

CREATE TABLE player_settings (
    id               varchar(36)      NOT NULL,
    player_id        varchar(36)      NOT NULL REFERENCES players (id),
    potion_threshold double precision NOT NULL,
    battle_log_count integer          NOT NULL,
    toast_enabled    boolean          NOT NULL,
    auto_sell_rarity varchar(20),
    PRIMARY KEY (id),
    CONSTRAINT uq_player_settings_player_id UNIQUE (player_id)
);

CREATE TABLE tower_clear_records (
    id            varchar(36) NOT NULL,
    player_id     varchar(36) NOT NULL REFERENCES players (id),
    tower_id      varchar(50) NOT NULL,
    cleared       boolean     NOT NULL,
    highest_floor integer     NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_tower_clear_records_player_tower UNIQUE (player_id, tower_id)
);

CREATE TABLE characters (
    id           varchar(36) NOT NULL,
    player_id    varchar(36) NOT NULL REFERENCES players (id),
    name         varchar(50) NOT NULL,
    type         varchar(20) NOT NULL,
    level        integer     NOT NULL,
    exp          bigint      NOT NULL,
    hp           integer     NOT NULL,
    max_hp       integer     NOT NULL,
    base_atk     integer     NOT NULL,
    base_def     integer     NOT NULL,
    base_spd     integer     NOT NULL,
    limit_break  integer     NOT NULL,
    skill_points integer     NOT NULL,
    created_at   timestamptz NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE party_members (
    id           varchar(36) NOT NULL,
    player_id    varchar(36) NOT NULL REFERENCES players (id),
    slot_index   integer     NOT NULL,
    character_id varchar(36) NOT NULL REFERENCES characters (id),
    PRIMARY KEY (id),
    CONSTRAINT uq_party_members_player_slot UNIQUE (player_id, slot_index),
    CONSTRAINT uq_party_members_player_character UNIQUE (player_id, character_id)
);

CREATE TABLE learned_skills (
    id                 varchar(36) NOT NULL,
    character_id       varchar(36) NOT NULL REFERENCES characters (id),
    skill_id           varchar(50) NOT NULL,
    cooldown_remaining integer     NOT NULL,
    learned_at         timestamptz NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_learned_skills_character_skill UNIQUE (character_id, skill_id)
);

CREATE TABLE active_skill_slots (
    id           varchar(36) NOT NULL,
    character_id varchar(36) NOT NULL REFERENCES characters (id),
    slot_index   integer     NOT NULL,
    skill_id     varchar(50) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_active_skill_slots_character_slot UNIQUE (character_id, slot_index)
);

-- ---------------------------------------------------------------------------
-- 装備・アイテム・ショップ（tech_db/item.md）
-- ---------------------------------------------------------------------------

CREATE TABLE equipment (
    id            varchar(36)      NOT NULL,
    player_id     varchar(36)      NOT NULL REFERENCES players (id),
    base_id       varchar(50)      NOT NULL,
    slot          varchar(20)      NOT NULL,
    rarity        varchar(20)      NOT NULL,
    level         integer          NOT NULL,
    enhance_level integer          NOT NULL,
    stat_atk      integer,
    stat_def      integer,
    stat_hp       integer,
    stat_spd      integer,
    lifesteal     double precision,
    is_two_handed boolean          NOT NULL,
    locked        boolean          NOT NULL,
    acquired_at   timestamptz      NOT NULL,
    PRIMARY KEY (id)
);

-- 主キーは (character_id, slot) の複合主キー（tech_db/item.md §2）
CREATE TABLE character_equip_slots (
    character_id varchar(36) NOT NULL REFERENCES characters (id),
    slot         varchar(20) NOT NULL,
    equipment_id varchar(36) REFERENCES equipment (id),
    PRIMARY KEY (character_id, slot)
);

CREATE TABLE inventory_items (
    id        varchar(36) NOT NULL,
    player_id varchar(36) NOT NULL REFERENCES players (id),
    item_id   varchar(50) NOT NULL,
    quantity  integer     NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_inventory_items_player_item UNIQUE (player_id, item_id)
);

CREATE TABLE shop_daily_states (
    id        varchar(36) NOT NULL,
    player_id varchar(36) NOT NULL REFERENCES players (id),
    reset_at  timestamptz NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_shop_daily_states_player_id UNIQUE (player_id)
);

CREATE TABLE shop_daily_slots (
    id                  varchar(36) NOT NULL,
    shop_daily_state_id varchar(36) NOT NULL REFERENCES shop_daily_states (id),
    slot_index          integer     NOT NULL,
    category            varchar(20) NOT NULL,
    base_id             varchar(50) NOT NULL,
    rarity              varchar(20) NOT NULL,
    level               integer     NOT NULL,
    stat_atk            integer,
    stat_def            integer,
    stat_hp             integer,
    stat_spd            integer,
    price               integer     NOT NULL,
    sold                boolean     NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_shop_daily_slots_state_slot UNIQUE (shop_daily_state_id, slot_index)
);

-- ---------------------------------------------------------------------------
-- 戦闘（tech_db/battle.md）
-- ---------------------------------------------------------------------------

-- timestamp 列は日時列の _at 規約の例外（tech_db/battle.md §1）。予約語のため引用符で囲む
CREATE TABLE battle_logs (
    id          varchar(36) NOT NULL,
    player_id   varchar(36) NOT NULL REFERENCES players (id),
    tick_number integer     NOT NULL,
    "timestamp" timestamptz NOT NULL,
    entries     json        NOT NULL,
    PRIMARY KEY (id)
);
