"""Phase2 daily shop tables

Phase 2: 日替わりショップ（ShopDailyState / ShopDailySlot）を追加する。
仕様: docs/tech/detail/tech_shop.md §5、ER図: docs/diagrams/er_diagram/item.md

Revision ID: 36e28dd936bc
Revises: 3685584aaa5b
Create Date: 2026-08-02 14:50:09.328326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e28dd936bc'
down_revision: Union[str, Sequence[str], None] = '3685584aaa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_daily_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_daily_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_daily_state_id', sa.String(length=36), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('base_id', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('stat_atk', sa.Integer(), nullable=True),
    sa.Column('stat_def', sa.Integer(), nullable=True),
    sa.Column('stat_hp', sa.Integer(), nullable=True),
    sa.Column('stat_spd', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('sold', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shop_daily_state_id'], ['shop_daily_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_daily_state_id', 'slot_index', name='uq_shop_daily_slot_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_daily_slots')
    op.drop_table('shop_daily_states')
    # ### end Alembic commands ###
